name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout Repo
        uses: actions/checkout@v2

      - name: ⚙️ Setting Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Creating .npmrc
        run: |
          cat << EOF > "./.npmrc"
           //registry.npmjs.org/:_authToken=$NPM_REGISTRY_TOKEN
          EOF
        env:
          NPM_REGISTRY_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
          version: yarn versioning
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}